### ISSUE TITLE
Update sub-content template for Accessibility

### ISSUE THREAD

**Issue by bobbinrobyn** [IBM-Watson/design-library#236]
Exchange the placeholder for the real deal, according to the templates in the [Content Models](https://github.com/IBM-Watson/design-library/wiki/Content-Models)

**Comment by bobbinrobyn** [comment]
@Snugug: Is this what we're aiming for?

These are the variables:
```
variables:
  detail:
    accessibilityInteraction:
        description: "When distinguishing an interactive element, do not rely on color as the only visual indicator."
        visualDisplay: images/accessibility/visual-accessibility-example.svg
        callouts: 
            title: "Help users to easily identify form elements by using iconography."
            description: "A log in page using iconography to help users identify input fields."
            title: "Help users to distinguish links by using combinations of colors and underlines."
            description: "A log in page using colored text and an underline to indicate a link."
    accessibilityAnimation:
        description: "When there is an animation that last longer than 5 seconds, provide the user a way to pause, stop, or hide the animation."
        visualDisplay: videos/accessibility/motion-accessibility.webm
```

This is the template:
`{{ _detail.view(detail.accessibilityInteraction) }}`

**Comment by Snugug** [comment]
@bobbinrobyn Yup!

**Comment by Snugug** [comment]
Although the callouts should look like:

```yaml
callouts:
  - title: "Help users to easily identify form elements by using iconography."
    description: "A log in page using iconography to help users identify input fields."
  - title: "Help users to distinguish links by using combinations of colors and underlines."
    description: "A log in page using colored text and an underline to indicate a link."
```

That way each title/description is paired as an item
